// AUTO-GENERATED by frontend/scripts/sync-tokens.cjs. Do not edit by hand.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "primary": {
          "50": "#fff5f0",
          "100": "#ffe8dd",
          "200": "#ffd1bb",
          "300": "#ffb999",
          "400": "#ffa277",
          "500": "#ff6b35",
          "600": "#e65620",
          "700": "#cc4116",
          "800": "#b32c0c",
          "900": "#991702"
        },
        "secondary": {
          "50": "#e6f2f8",
          "100": "#cce5f1",
          "200": "#99cbe3",
          "300": "#66b1d5",
          "400": "#3397c7",
          "500": "#004e89",
          "600": "#003d6b",
          "700": "#002c4d",
          "800": "#001b2f",
          "900": "#000a11"
        },
        "success": {
          "50": "#e8f5e9",
          "100": "#c8e6c9",
          "500": "#28a745",
          "600": "#239b3e",
          "700": "#1e8e37",
          "800": "#198230",
          "900": "#146c29"
        },
        "warning": {
          "50": "#fff8e1",
          "100": "#ffecb3",
          "500": "#ffc107",
          "600": "#ffb300",
          "700": "#ffa000",
          "800": "#ff8f00",
          "900": "#ff6f00"
        },
        "error": {
          "50": "#ffebee",
          "100": "#ffcdd2",
          "400": "#ef5350",
          "500": "#dc3545",
          "600": "#d32f2f",
          "700": "#c62828",
          "800": "#b71c1c",
          "900": "#a50f15"
        },
        "info": {
          "50": "#e6f2f8",
          "100": "#cce5f1",
          "200": "#99cbe3",
          "300": "#66b1d5",
          "400": "#3397c7",
          "500": "#004e89",
          "600": "#003d6b",
          "700": "#002c4d",
          "800": "#001b2f",
          "900": "#000a11"
        },
        "neutral": {
          "0": "#ffffff",
          "50": "#f8f9fa",
          "100": "#f1f3f5",
          "200": "#e9ecef",
          "300": "#dee2e6",
          "400": "#ced4da",
          "500": "#adb5bd",
          "600": "#6c757d",
          "700": "#495057",
          "800": "#343a40",
          "900": "#212529",
          "1000": "#000000"
        },
        "border": {
          "DEFAULT": "#dee2e6",
          "strong": "#adb5bd",
          "focus": "#e65620"
        },
        "surface": {
          "DEFAULT": "#ffffff",
          "elevated": "#ffffff",
          "subtle": "#f1f3f5"
        }
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "'Helvetica Neue'",
          "Arial",
          "sans-serif"
        ],
        "mono": [
          "'JetBrains Mono'",
          "'Fira Code'",
          "'Courier New'",
          "monospace"
        ]
      },
      "fontSize": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem"
      },
      "borderRadius": {
        "none": "0px",
        "sm": "0.25rem",
        "base": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "624.9375rem"
      },
      "spacing": {
        "0": "0px",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
        "0.5": "0.125rem",
        "1.5": "0.375rem",
        "2.5": "0.625rem",
        "3.5": "0.875rem"
      },
      "boxShadow": {
        "none": "none",
        "sm": "0 1px 3px rgba(0, 0, 0, 0.10)",
        "md": "0 10px 15px rgba(0, 0, 0, 0.10)",
        "lg": "0 20px 25px rgba(0, 0, 0, 0.10)"
      },
      "transitionDuration": {
        "instant": "0ms",
        "fast": "150ms",
        "base": "200ms",
        "slow": "300ms"
      },
      "transitionTimingFunction": {
        "linear": "linear",
        "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
        "out": "cubic-bezier(0, 0, 0.2, 1)"
      }
    }
  }
};
