#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..', '..');
const frontendRoot = path.join(repoRoot, 'frontend');
const tokenPath = path.join(frontendRoot, 'design-tokens.json');
const staleTokenCopy = path.join(frontendRoot, 'src', 'design-tokens.json');
const checkMode = process.argv.includes('--check');
const header = 'AUTO-GENERATED by frontend/scripts/sync-tokens.cjs. Do not edit by hand.';

const tokens = JSON.parse(fs.readFileSync(tokenPath, 'utf8'));

function ensureDir(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function get(obj, dotted) {
  return dotted.split('.').reduce((current, key) => current?.[key], obj);
}

function resolve(value) {
  if (typeof value !== 'string') return value;
  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return value;
  const ref = match[1];
  if (ref.startsWith('color.')) {
    return resolve(get(tokens.primitives, ref));
  }
  if (ref.startsWith('semantic.')) {
    return resolve(get(tokens, ref));
  }
  return resolve(get(tokens.primitives, ref));
}

function flatten(node, prefix = []) {
  const entries = [];
  for (const [key, value] of Object.entries(node)) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      entries.push(...flatten(value, [...prefix, key]));
    } else {
      entries.push([[...prefix, key], resolve(value)]);
    }
  }
  return entries;
}

function cssVarName(parts) {
  return `--mm-${parts.join('-').replace(/_/g, '-')}`;
}

function cssValue(value) {
  return String(value);
}

function cssOutput() {
  const lines = [`/* ${header} */`, ':root {'];
  for (const [parts, value] of flatten(tokens.primitives)) {
    lines.push(`  ${cssVarName(parts)}: ${cssValue(value)};`);
  }
  for (const [parts, value] of flatten(tokens.semantic.light)) {
    lines.push(`  ${cssVarName(['semantic', ...parts])}: ${cssValue(value)};`);
  }
  for (const [parts, value] of flatten(tokens.components)) {
    lines.push(`  ${cssVarName(['component', ...parts])}: ${cssValue(value)};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('[data-theme="dark"], .dark {');
  for (const [parts, value] of flatten(tokens.semantic.dark)) {
    lines.push(`  ${cssVarName(['semantic', ...parts])}: ${cssValue(value)};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push('  :root {');
  lines.push('    --mm-motion-duration-fast: 0ms;');
  lines.push('    --mm-motion-duration-base: 0ms;');
  lines.push('    --mm-motion-duration-slow: 0ms;');
  lines.push('  }');
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

function colorRamp(name) {
  return tokens.primitives.color[name];
}

function rem(value) {
  const match = String(value).match(/^(\d+(?:\.\d+)?)px$/);
  if (!match) return value;
  const px = Number(match[1]);
  return px === 0 ? '0px' : `${px / 16}rem`;
}

function tailwindOutput() {
  const spacing = {};
  for (const [key, value] of Object.entries(tokens.primitives.spacing)) {
    spacing[key.replace('_', '.')] = rem(value);
  }
  const tailwindTokens = {
    theme: {
      extend: {
        colors: {
          primary: colorRamp('orange'),
          secondary: colorRamp('blue'),
          success: colorRamp('green'),
          warning: colorRamp('yellow'),
          error: colorRamp('red'),
          info: colorRamp('blue'),
          neutral: tokens.primitives.color.neutral,
          border: {
            DEFAULT: resolve(tokens.semantic.light.border.default),
            strong: resolve(tokens.semantic.light.border.strong),
            focus: resolve(tokens.semantic.light.border.focus),
          },
          surface: {
            DEFAULT: resolve(tokens.semantic.light.background.surface),
            elevated: resolve(tokens.semantic.light.background.surface_elevated),
            subtle: resolve(tokens.semantic.light.background.subtle),
          },
        },
        fontFamily: {
          sans: tokens.primitives.typography.family.sans.split(', '),
          mono: tokens.primitives.typography.family.mono.split(', '),
        },
        fontSize: Object.fromEntries(
          Object.entries(tokens.primitives.typography.size).map(([key, value]) => [key, rem(value)])
        ),
        borderRadius: Object.fromEntries(
          Object.entries(tokens.primitives.radius).map(([key, value]) => [key, rem(value)])
        ),
        spacing,
        boxShadow: tokens.primitives.elevation,
        transitionDuration: tokens.primitives.motion.duration,
        transitionTimingFunction: tokens.primitives.motion.easing,
      },
    },
  };
  return `// ${header}\nmodule.exports = ${JSON.stringify(tailwindTokens, null, 2)};\n`;
}

function androidColor(hex) {
  return `0xFF${hex.replace('#', '').toUpperCase()}`;
}

function ktIdentifier(parts) {
  return parts
    .map((part) => part.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase()))
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function androidKotlinOutput() {
  const lines = [
    `// ${header}`,
    'package com.menumaker.ui.theme',
    '',
    'import androidx.compose.ui.graphics.Color',
    '',
    'object GeneratedTokens {',
    '  const val BrandNamespace = "menumaker"',
    '  const val MinimumTouchTargetDp = 48',
  ];
  for (const [parts, value] of flatten(tokens.primitives.color)) {
    lines.push(`  val Color${ktIdentifier(parts)} = Color(${androidColor(value)})`);
  }
  for (const [parts, value] of flatten(tokens.semantic.light)) {
    if (String(value).startsWith('#')) {
      lines.push(`  val Light${ktIdentifier(parts)} = Color(${androidColor(value)})`);
    }
  }
  for (const [parts, value] of flatten(tokens.semantic.dark)) {
    if (String(value).startsWith('#')) {
      lines.push(`  val Dark${ktIdentifier(parts)} = Color(${androidColor(value)})`);
    }
  }
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

function resourceName(parts) {
  return `mm_${parts.join('_').replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase()}`;
}

function androidXmlOutput() {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, `<!-- ${header} -->`, '<resources>'];
  for (const [parts, value] of flatten(tokens.primitives.color)) {
    lines.push(`  <color name="${resourceName(['color', ...parts])}">${value.toUpperCase()}</color>`);
  }
  for (const [parts, value] of flatten(tokens.semantic.light)) {
    if (String(value).startsWith('#')) {
      lines.push(`  <color name="${resourceName(['semantic_light', ...parts])}">${value.toUpperCase()}</color>`);
    }
  }
  lines.push('</resources>');
  return `${lines.join('\n')}\n`;
}

function swiftColorLiteral(hex) {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.slice(0, 2), 16) / 255;
  const g = parseInt(clean.slice(2, 4), 16) / 255;
  const b = parseInt(clean.slice(4, 6), 16) / 255;
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
}

function swiftOutput() {
  const lines = [
    `// ${header}`,
    'import SwiftUI',
    '',
    'enum GeneratedTokens {',
    '    static let brandNamespace = "menumaker"',
    '    static let minimumTouchTarget: CGFloat = 44',
    '',
    '    enum Light {',
  ];
  for (const [parts, value] of flatten(tokens.semantic.light)) {
    if (String(value).startsWith('#')) {
      lines.push(`        static let ${parts.join('_')} = ${swiftColorLiteral(value)}`);
    }
  }
  lines.push('    }');
  lines.push('');
  lines.push('    enum Dark {');
  for (const [parts, value] of flatten(tokens.semantic.dark)) {
    if (String(value).startsWith('#')) {
      lines.push(`        static let ${parts.join('_')} = ${swiftColorLiteral(value)}`);
    }
  }
  lines.push('    }');
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

function assetColorInputOutput() {
  const colors = {};
  for (const [parts, value] of flatten(tokens.semantic.light)) {
    if (String(value).startsWith('#')) {
      colors[`light.${parts.join('.')}`] = value;
    }
  }
  for (const [parts, value] of flatten(tokens.semantic.dark)) {
    if (String(value).startsWith('#')) {
      colors[`dark.${parts.join('.')}`] = value;
    }
  }
  return `${JSON.stringify({ generated_by: 'frontend/scripts/sync-tokens.cjs', brand: tokens.brand.namespace, colors }, null, 2)}\n`;
}

const outputs = new Map([
  [path.join(frontendRoot, 'src', 'styles', 'tokens.css'), cssOutput()],
  [path.join(frontendRoot, 'tailwind-tokens.cjs'), tailwindOutput()],
  [path.join(repoRoot, 'android', 'app', 'src', 'main', 'kotlin', 'com', 'menumaker', 'ui', 'theme', 'GeneratedTokens.kt'), androidKotlinOutput()],
  [path.join(repoRoot, 'android', 'app', 'src', 'main', 'res', 'values', 'generated_colors.xml'), androidXmlOutput()],
  [path.join(repoRoot, 'ios', 'MenuMaker', 'Shared', 'Theme', 'GeneratedTokens.swift'), swiftOutput()],
  [path.join(repoRoot, 'ios', 'MenuMaker', 'Generated', 'DesignTokens', 'asset-colors.json'), assetColorInputOutput()],
]);

let failed = false;
for (const [file, expected] of outputs) {
  if (checkMode) {
    const actual = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (actual !== expected) {
      console.error(`❌ generated token output is stale: ${path.relative(repoRoot, file)}`);
      failed = true;
    }
  } else {
    ensureDir(file);
    fs.writeFileSync(file, expected);
  }
}

if (checkMode) {
  if (fs.existsSync(staleTokenCopy)) {
    console.error(`❌ stale token copy must be removed: ${path.relative(repoRoot, staleTokenCopy)}`);
    failed = true;
  }
  if (failed) process.exit(1);
  console.log('✅ generated token outputs are current');
} else {
  if (fs.existsSync(staleTokenCopy)) {
    fs.unlinkSync(staleTokenCopy);
  }
  console.log('✅ generated token outputs updated');
}
